spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/springtest
    username: sa
    password:
    driver-class-name: org.h2.Driver

#logging:
#  level:
#    org:
#      springframework:
#        jdbc: debug
